# Sunucu Portu
server.port=8080

# PostgreSQL & PostGIS Veri Tabanı Bağlantısı
spring.datasource.url=jdbc:postgresql://localhost:5432/routecharge_db
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA / Hibernate Ayarları (Hibernate 6+ İçin Güncel Diyalekt)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true